from django.urls import path, include, re_path
from .views import *
from django_email_verification import urls as email_urls
from . import views
# from verify_email import urls as mail_urls  #MIGHT HAVE ERROR

app_name = "marineapp"
urlpatterns = [
    #     path("", HomeView.as_view(), name="home"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("", LogInView.as_view(), name="login"),
    path("logout/", LogOutView.as_view(), name="logout"),
    path("maindashboard/", MainDashboardView.as_view(), name="maindashboard"),
    # path('verification/', VerificationView.as_view(), name='verify_email'),
    re_path('^send_email/$', sendEmail),
    path('email/', include(email_urls)),
    path("maindashboard/hrdashboard/",
         HRDashboardView.as_view(),
         name="hrdashboard"),
    path("maindashboard/traineedashboard/",
         TraineeDashboardView.as_view(),
         name="traineedashboard"),
    path("maindashboard/trainerdashboard/",
         TrainerDashboardView.as_view(),
         name="trainerdashboard"),
    ###
#     path("quiz1/", Quiz1View.as_view(), name="quiz1form"),
    #     path("quiz1question/",
    #          Quiz1QuestionView.as_view(),
    #          name="quiz1questionform"),
    #     path("quiz1answers/", Quiz1AnswerView.as_view(), name="quiz1formanswers"),
    #####
    path("maindashboard/virtual-tour/",
         VirtualTourView.as_view(),
         name="virtualtour"),
    path("match-learn-instructions/",
         MatchInstructionView.as_view(),
         name="matchinstruction"),
    path("module1-lesson/", Module1LessonView.as_view(), name="module1lesson"),
    path("match-game/", MatchGameView.as_view(), name="matchgame"),
    path("module2-lesson/", Module2LessonView.as_view(), name="module2lesson"),
    path("module3-lesson/", Module3LessonView.as_view(), name="module3lesson"),
    path("module4-lesson/", Module4LessonView.as_view(), name="module4lesson"),
    path("module5-lesson/", Module5LessonView.as_view(), name="module5lesson"),
    path("hangman-instruction/",
         HangmanInstructionView.as_view(),
         name="hangmaninstruction"),
    path("match-game/", MatchGameView.as_view(), name="matchgame"),
    path("hangman-game/", HangmanGameView.as_view(), name="hangmangame"),
    path("lessonmaterial-module1/",
         LessonMaterialModule1View.as_view(),
         name="lessonmaterialmodule1"),
    path("lessonmaterial-module1/",
         LessonMaterialModule1View.as_view(),
         name="lessonmaterialmodule1"),
    path("lessonmaterial-module2/",
         LessonMaterialModule2View.as_view(),
         name="lessonmaterialmodule2"),
    path("lessonmaterial-module3/",
         LessonMaterialModule3View.as_view(),
         name="lessonmaterialmodule3"),
    path("lessonmaterial-module4/",
         LessonMaterialModule4View.as_view(),
         name="lessonmaterialmodule4"),
    path("lessonmaterial-module5/",
         LessonMaterialModule5View.as_view(),
         name="lessonmaterialmodule5"),
    path("engine-room/", EngineRoomView.as_view(), name="engineroom"),
    path("delete_topic/(?P<module>[0-9]+)$/(?P<topic>[0-9]+)$", DeleteRowView.as_view(), name="deleterow"),

]