# Generated by Django 3.2.8 on 2021-11-17 10:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterialModule1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('pdf_file', models.FileField(upload_to='lesson_module1')),
            ],
            options={
                'verbose_name_plural': 'Module 1 Lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterialModule2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('pdf_file', models.FileField(upload_to='lesson_module2')),
            ],
            options={
                'verbose_name_plural': 'Module 2 Lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterialModule3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('pdf_file', models.FileField(upload_to='lesson_module3')),
            ],
            options={
                'verbose_name_plural': 'Module 3 Lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterialModule4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('pdf_file', models.FileField(upload_to='lesson_module4')),
            ],
            options={
                'verbose_name_plural': 'Module 4 Lesson',
            },
        ),
        migrations.CreateModel(
            name='LessonMaterialModule5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=1000)),
                ('pdf_file', models.FileField(upload_to='lesson_module5')),
            ],
            options={
                'verbose_name_plural': 'Module 5 Lesson',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254)),
                ('hr', models.BooleanField(default=False, verbose_name='HR')),
                ('trainer', models.BooleanField(default=False, verbose_name='Trainer')),
                ('trainee', models.BooleanField(default=False, verbose_name='Trainee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User- HR, Trainee, Trainer',
            },
        ),
    ]
